
title: Mirko Cerovac Resume
# url: 'http://webjeda.com'
baseurl: '/mirko-cerovac-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Mirko Cerovac
tagline: Ruby on Rails Developer
pic: mirko.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: mirko.cerovac@gmail.com
phone: +385 91 604 6168
linkedin: mirkocerovac
github: MirkoC
# twitter: '@MCerovac'

#Update all the sections by editing the files inside _includes folder.
